#!/bin/bash
# Run sbt scalafmtAll
sbt scalafmtAll
# Check if any files were modified
if git diff-index --quiet HEAD --; then
    echo "No files were modified by scalafmt"
else
    echo "Some files were modified by scalafmt"
    git add .
    git commit --amend --no-edit
fi
